export const reducerCases = {
    SET_TOKEN:"SET_TOKEN",
    SET_PLAYLISTS: "SET_PLAYLISTS",
    SET_USER: "SET_USER",
    SET_PLAYLIST: "SET_PLAYLIST",
    SET_PLAYING: "SET_PLAYING",
    SET_PLAYER_STATE: "SET_PLAYER_STATE",
    SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
    SET_TOKEN_EXPIRED: "SET_TOKEN_EXPIRED",
    SET_CURRENT_AUDIO_SRC :"SET_CURRENT_AUDIO_SRC",
    SET_REDIRECT_URL :"SET_REDIRECT_URL",
    SET_SEARCH_KEY: "SET_SEARCH_KEY",
    SET_SEARCH_RESULTS: "SET_SEARCH_RESULTS",
}